version: "3.8"

services:
  backend:
    build:
      context: ./api
    ports:
      - "8000:8000"
    volumes:
      - ./api:/app
    restart: always

  frontend:
    build:
      context: ./frontend/dog-classifier-app
    ports:
      - "3000:80"
    restart: always
    depends_on:
      - backend
